app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_exchange.urls')),
]

app_exchange/urls.py
from django.urls import path
from .views import ExchangeView

app_name = 'exchange'

urlpatterns = [
    path('', ExchangeView.as_view(), name='form')
]

app_exchange/models.py
from django.db import models

# Create your models here.

app_exchange/forms.py
from django import forms
from app_exchange.services.exchange import get_currency_code_list


class ExchangeForm(forms.Form):
    """Форма обмена валют"""

    CODE_LIST = get_currency_code_list()

    amount = forms.IntegerField(label='Amount', min_value=1, max_value=1000000)
    currency_from = forms.ChoiceField(label='From', choices=CODE_LIST)
    currency_to = forms.ChoiceField(label='To', choices=CODE_LIST)

app_exchange/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from app_exchange.forms import ExchangeForm
from app_exchange.services.exchange import get_exchange_result
from app_exchange.utils import json_responce_success, json_responce_form_errors, json_responce_server_errors


class ExchangeView(View):
    """Представление формы"""

    def get(self, request):
        """Обработка get запроса"""
        form = ExchangeForm()
        return render(request, template_name='app_exchange/index.html', context={'form': form})

    def post(self, request):
        """Обработка post запроса"""
        if self._is_ajax(request):
            form = ExchangeForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                result = get_exchange_result(
                    amount=cd['amount'], currency_code_from=cd['currency_from'], currency_code_to=cd['currency_to']
                )
                return JsonResponse(json_responce_success(result=result), status=200)
            else:
                return JsonResponse(json_responce_form_errors(errors=form.errors), status=200)

        return JsonResponse(json_responce_server_errors(), status=200)

    def _is_ajax(self, request):
        """Проверяем метод запроса на ajax"""
        return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

templates/app_exchange/index.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="text-center p-3">Currency Exchange</h3>
    <div class="mt-2 p-3 text-center border border-1">
        <form id="form" method="post" class="row g-3">
            {% csrf_token %}
            {% for field in form %}
                <div class="col-auto">
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            <div class="col-auto">
                <input id="convert" class="btn btn-primary btn-sm" type="button" value="Convert">
            </div>
        </form>
        <div id="id_non_field_errors"></div>
    </div>
    <div class="mt-2 p-3 text-center border border-1 text-success fs-5" id="result-block" style="display: none;">
        <span id="result_amount"></span> <span id="result_from"></span> =
        <span id="result">{{ result }}</span> <span id="result_to"></span>
    </div>
{% endblock %}

{% block javascript %}
<script>
$(document).ready(function(){
    $('#convert').on('click', function(e){
        $.ajax({
            url: "{% url 'exchange:form' %}",
            method: 'POST',
            data: {
                amount: $('#id_amount').val(),
                currency_from: $('#id_currency_from').val(),
                currency_to: $('#id_currency_to').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function(response) {
                $(".text-danger").remove();
                if (response.success) {
                    $('#result-block').show()
                    $('.text-danger').hide()
                    $('#result').text(response.result)
                    $('#result_amount').text($('#id_amount').val())
                    $('#result_from').text($('#id_currency_from').val())
                    $('#result_to').text($('#id_currency_to').val())
                } else {
                    $('#result-block').hide()
                    $.each(JSON.parse(response.errors), function(index, value) {
                        $.each(value, function(i, val) {
                            $('<div class="text-danger">' + val.message + '</div>').insertAfter("#id_" + index);
                        })
                    })
                }
            },
        });
    });
});
</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Exchange currency</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="d-flex align-items-center justify-content-center vh-100">
        <div class="shadow p-2 rounded ">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>